const endPoints = {
	guestLogin: 'EwayCommonApi/authentication/doauth',
	login: 'EwayCommonApi/authentication/login',
	currencyList: 'EwayCommonApi/master/dropdown/productcurrency',
	motorMake: 'EwayCommonApi/master/dropdown/motormake',
	modelList: 'EwayCommonApi/master/dropdown/motormakemodel',
	bodyTypeList: 'EwayCommonApi/master/dropdown/induvidual/bodytype',
	vehicleUsage: 'EwayCommonApi/api/dropdown/induvidual/vehicleusage',
	saveMotorDetails: 'EwayMotorApi/api/savemotordetails',
	policyEndDates: 'EwayCommonApi/dropdown/policyEndDate',
	generateOTP: 'EwayCommonApi/otp/generate',
	verifyOTP: 'EwayCommonApi/otp/validate',
	insuranceClass: 'EwayAdminApi/master/dropdown/policytype',
	calculator: 'EwayCommonApi/calculator/calc',
	viewCalculated: 'EwayCommonApi/api/view/calc',
	saveCustomer: 'EwayCommonApi/api/savecustomerdetails',
	saveVehicle: 'EwayMotorApi/regulatory/savevehicleinfo',
	occupationList: 'EwayCommonApi/master/dropdown/occupation',
	regionList: 'EwayCommonApi/master/dropdown/region',
	colorList: 'EwayCommonApi/master/dropdown/color',
	documentType: 'EwayCommonApi/document/dropdown/doctypes',
	buyPolicy: 'EwayCommonApi/quote/buypolicy',
	viewQuote: 'EwayCommonApi/quote/viewquotedetails',
	uploadFile: 'EwayCommonApi/document/upload',
	bankList: 'EwayCommonApi/master/dropdown/bankmaster',
	registrationToken: 'EwayCommonApi/madison/get/token',
	registrationDetails: 'EwayCommonApi/madison/get/RegDetails',
	vehicleList: 'EwayCommonApi/madison/get/Rtsalist'
}
export default endPoints
