'use client'

import { Camera, Info } from 'lucide-react'

import { FileUploader } from 'react-drag-drop-files'
import Image from 'next/image'
import { assets } from '@/assets'
import { useGSAP } from '@gsap/react'
import gsap from 'gsap'

export function WhiteBook() {
	useGSAP(() => {
		gsap.to('.title', { duration: 0.5, text: 'Upload your whitebook' })
		gsap.to('.subtitle', {
			duration: 0.5,
			text: 'Fill out the vehicle and customer details section completely with AI',
			delay: 0.5
		})
	})

	return (
		<>
			<FileUploader
				id='fileUpload'
				label='Drag and Drop Files Here'
				name='file'>
				<div className='flex flex-col gap-1'>
					<div className='-ml-16 flex flex-row gap-4'>
						<div className='h-12 w-12 overflow-hidden rounded-full'>
							<Image
								alt='face'
								height={60}
								src={assets.images.imageFace}
								width={60}
							/>
						</div>
						<div className='flex flex-col gap-2'>
							<h1 className='title font-jakarta text-xl font-semibold text-black' />
							<p className='subtitle font-roboto text-sm' />
						</div>
					</div>
					<div className='bg-fadedNeon w-full items-center rounded-3xl p-2'>
						<div className='flex cursor-pointer flex-row justify-center gap-4 rounded-3xl bg-[#E7FAF4] py-4 font-bold'>
							<Camera color='#4ade80' />
							<p className='text-green-400'>Upload your Whitebook</p>
						</div>
					</div>
					<div className='flex flex-row items-center gap-2'>
						<Info
							color='#337AB7'
							height={16}
							width={16}
						/>
						<p className='font-roboto text-sm text-gray-800'>
							Disclaimer : The below filled information are auto-generated by AI, to
							continue please check once
						</p>
					</div>
				</div>
			</FileUploader>
			<div className='flex items-center justify-center opacity-50'>
				<div className='relative w-full border-t border-green-50'>
					<span className='absolute left-1/2 top-0 -translate-x-1/2 -translate-y-1/2 transform bg-white px-2 font-roboto font-semibold'>
						Or
					</span>
				</div>
			</div>
		</>
	)
}
