'use client'

import { FileUploader } from 'react-drag-drop-files'
import OnboardingLayout from './OnboardingLayout'
import { CloudUpload, Info } from 'lucide-react'
import { Label } from '../ui/label'
import { Button, Input } from '../ui'
import { useRouter } from 'next/navigation'

export default function OnboardingInfoPage() {
	const route = useRouter()

	function getMotorDetails() {
		route.push('/car-insurance/1')
	}

	return (
		<OnboardingLayout>
			<div className='flex h-full w-full items-center justify-center'>
				<div className='flex h-full flex-col items-center justify-center gap-6 px-6 py-6 font-roboto lg:items-start lg:gap-12 lg:py-0 lg:pr-10'>
					<div className='flex flex-col items-center justify-around gap-10 font-roboto'>
						<div className='flex flex-col items-center gap-6'>
							<h1 className='text-3xl font-medium lg:text-4xl'>
								Apply a Insurance in 2 Mins
							</h1>
							<div className='relative mr-auto w-3/4 border-4 border-blue-300'></div>
							<span className='max-w-[340px] text-center'>
								Upload your Whitebook or registration number
							</span>
						</div>
						<div className='flex flex-col gap-3'>
							<FileUploader
								classes='w-full rounded-md border-blue-450 border-dashed border-2 flex flex-col gap-2 items-center justify-center font-jakarta py-6'
								id='fileUpload'
								label='Drag and Drop Files Here'
								name='file'>
								<CloudUpload
									color='#1849D6'
									height={36}
									strokeWidth={2}
									width={36}
								/>
								<h3 className='text-sm font-semibold'>
									Drag your file(s) or{' '}
									<span className='text-blue-450'>browse</span>
								</h3>
								<h4 className='text-sm text-gray-435'>Upload your Whitebook</h4>
							</FileUploader>
							<div className='flex flex-row items-center gap-2'>
								<Info
									color='#337AB7'
									height={16}
									width={16}
								/>
								<p className='font-roboto text-xs text-gray-800'>
									Disclaimer : The below filled information are auto-generated by
									AI, to continue please check once
								</p>
							</div>
						</div>
					</div>
					<div className='flex w-full items-center justify-center opacity-50'>
						<div className='relative w-full border-t border-green-50'>
							<span className='absolute left-1/2 top-0 -translate-x-1/2 -translate-y-1/2 transform bg-white px-2 font-roboto font-semibold'>
								Or
							</span>
						</div>
					</div>
					<div className='flex w-full flex-col items-center justify-around gap-10 font-roboto'>
						<div className='flex w-full flex-col gap-1'>
							<Label htmlFor='registrationNo'>Registration number</Label>
							<Input
								className='w-full'
								id='registrationNo'
								placeholder='Enter your registration number'
							/>
							<div className='flex flex-row items-center gap-2'>
								<Info
									color='#337AB7'
									height={14}
									width={14}
								/>
								<p className='font-roboto text-xs text-gray-800'>
									Enter your existing policy number to access your account within
									single click
								</p>
							</div>
						</div>
					</div>
					<Button
						className='w-full'
						variant='bluebtn'
						onClick={getMotorDetails}>
						Submit
					</Button>
				</div>
			</div>
		</OnboardingLayout>
	)
}
