import { AppProvider } from '@/components/app-provider'
import { cn, fonts } from '@/lib'
import { type Metadata } from 'next'
import { type PropsWithChildren } from 'react'
import './globals.css'
import { Toaster } from '@/components/ui/toaster'

const fontVariables = fonts.map((f) => f.variable)

export const metadata: Metadata = {
	title: 'Madison',
	description: 'Generated by create next app'
}

export default function Layout(props: PropsWithChildren) {
	return (
		<html lang='en'>
			<AppProvider>
				<body className={cn(fontVariables, 'bg-mainBg')}>
					<>
						{props.children}
						<Toaster />
					</>
				</body>
			</AppProvider>
		</html>
	)
}
